### ISSUE TITLE
Change the project name

### ISSUE THREAD

**Issue by csbubbles** [cforce/redcase_branch#3]
Hi Terence,

I am writing on behalf of the team which created actual Redcase (https://sourceforge.net/projects/redcase/). We are going to continue our development, therefore, I would like to ask you to change the name of this project. As we provide our plugin under MIT license you can do whatever you want with source code, docs and anything we ship in packages, but we would really appreciate if you change the name of your project not to confuse users with the original product.

Regards,
Maxim.

**Comment by cforce** [comment]
My inntetion was to give users a way to submit issues for redcase and make it possible to contribute sourcecode, as this can't be done on sourceforge properly.
I apprecaite you start over again, but please use hithub or at least a mirror on github.
 I will remove this püroject as soons you took over the openb issue reports, because this reports main errors making redcase unusable at the moment.
Please also add localization to this plugin.

**Comment by anikievev** [comment]
Hi!
As one of Redcase's founder I support Maxim opinion. I suggest to change name of this project.

**Comment by cforce** [comment]
Well, i am still waiting for your new release to come out. When we can see this effort?

**Comment by csbubbles** [comment]
Hi Terence, we are going to issue the beta in 1 - 2 months. I have sent you an email (I hope that address on gmx.de is yours) with more details.
